admin_ajouter_patho:
    path:     /ajouter_patho
    defaults: { _controller: AdminBundle:Admin:ajouter_patho }

admin_supprimer_patho:
    path:     /supprimer_patho
    defaults: { _controller: AdminBundle:Admin:supprimer_patho }

admin_lister_patho:
    path:     /lister_patho
    defaults: { _controller: AdminBundle:Admin:lister_patho }
