admin_ajouter_patho:
    path:     /ajouter_patho
    defaults: { _controller: AdminBundle:Admin:ajouter_patho }

admin_supprimer_patho:
    path:     /supprimer_patho
    defaults: { _controller: AdminBundle:Admin:supprimer_patho }
    
admin_suppr_patho:
    path:     /suppr_patho
    defaults: { _controller: AdminBundle:Admin:suppr_patho }

admin_lister_patho:
    path:     /lister_patho
    defaults: { _controller: AdminBundle:Admin:lister_patho }

admin_Patho_existente:
    path:     /patho_existante
    defaults: { _controller: AdminBundle:Admin:patho_existante }

admin_Patho_inconnu:
    path:     /patho_inconnu
    defaults: { _controller: AdminBundle:Admin:patho_inconnu }

admin_bdd_vide_patho:
    path:     /bdd_vide_patho
    defaults: { _controller: AdminBundle:Admin:bdd_vide_patho }

reserve_admin:
    path:     /reserve_admin
    defaults: { _controller: AdminBundle:Admin:reserve_admin }
