admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:  /login
    defaults: { _controller: UserBundle:Security:login }
 
login_check:
    pattern:  /login_check

logout:
    pattern:  /logout

sdz_blog:
    resource: "@SdzBlogBundle/Resources/config/routing.yml"
    prefix:   /blog

app:
    resource: "@AppBundle/Controller/"
    type:     annotation


