# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html

security:
    encoders:
        # Symfony\Component\Security\Core\User\User: plaintext
        AdminBundle\Entity\Compte: sha512
        
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        main:
            id: fos_user.user_provider.username
            # entity: { class: AdminBundle\Entity\Compte, property: user }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:    ^/(_(profiler|wdt)|css|images|js)/
            security:   false
        
        main_accueil:
            pattern:    ^/accueil$
            anonymous:   true
            
        main_login:
            pattern:    ^/login$
            anonymous:   true
            
        main_register:
            pattern:    ^/register$
            anonymous:   true
            
        main_nouscontacter:
            pattern:    ^/nous_contacter$
            anonymous:   true
                 
        main:
            pattern:    ^/
            anonymous:  false
            provider:   main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:    fos_user_security_logout
                target:  /accueil
            remember_me:
                key:     %secret%
            # %secret% est un parametre de parametre.yml
            
            
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
