<?php

namespace AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Banque_PathoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Banque_PathoRepository extends EntityRepository
{
}
