<?php

namespace AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IndividuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndividuRepository extends EntityRepository
{
	
	public function findIndividusCompte()
	{
		$qb = $this
			->createQueryBuilder('i')
			->leftJoin('i.compte', 'id')
			->addSelect('id')
	
	;
	
	
	return $qb
	
    ->getQuery()
	
    ->getResult()
	
	;
	}
}
