###
user_connected_index:
    path:     /user
    defaults: {_controller:UserBundle:User:index }

###
user_accueil:
    path:     /accueil
    defaults: { _controller:UserBundle:User:accueil }

###
user_ajout_proche:
    path:     /ajout_proche
    defaults: { _controller:UserBundle:User:ajout_proche }

# user_modif_proche:
#     path:     /modif_proche
#     defaults: { _controller:UserBundle:User:modif_proche }

user_modif_proche:
    path:     /modif_proche/{id_indiv}
    defaults: { _controller:UserBundle:User:modif_proche }

user_suppr_proche:
    path:     /suppr_proche/{id_indiv}
    defaults: { _controller:UserBundle:User:suppr_proche }

user_liste_patho_proche:
    path:     /liste_patho_proche/{id_indiv}
    defaults: { _controller:UserBundle:User:liste_patho_proche }
user_liste_patho_proche_vide:
    path:     /liste_patho_proche_vide/{id_indiv}
    defaults: { _controller:UserBundle:User:liste_patho_proche_vide }

user_ajout_patho_proche:
    path:     /ajout_patho_proche/{id_indiv}
    defaults: { _controller:UserBundle:User:ajout_patho_proche }

user_modif_patho_proche:
    path:     /modif_patho_proche{id_indiv}
    defaults: { _controller:UserBundle:User:modif_patho_proche }

user_suppr_patho_proche:
    path:     /suppr_patho_proche/{id_indiv}
    defaults: { _controller:UserBundle:User:suppr_patho_proche }

###
user_liste_proches:
    path:    /liste_proches
    defaults: { _controller:UserBundle:User:liste_proches }
###
user_liste_proches_vide:
    path:    /liste_proches_vide
    defaults: { _controller:UserBundle:User:liste_proches_vide }

user_liste_relation:
    path:    /liste_relation/{id_indiv}
    defaults: { _controller:UserBundle:User:liste_relation }

user_liste_relation_vide:
    path:    /liste_relation_vide/{id_indiv}
    defaults: { _controller:UserBundle:User:liste_relation_vide }

user_ajout_relation:
    path:    /ajout_relation/{id_indiv}
    defaults: { _controller:UserBundle:User:ajout_relation }

user_modif_relation:
    path:    /modif_relation/{id_indivA}/{id_indivB}
    defaults: { _controller:UserBundle:User:modif_relation }

user_suppr_relation:
    path:    /suppr_relation/{id_indivA}/{id_indivB}
    defaults: { _controller:UserBundle:User:suppr_relation }

user_liste_patho_proches:
    path:    /liste_patho_proches
    defaults: { _controller:UserBundle:User:liste_patho_proches }
user_liste_patho_proches_vide:
    path:    /liste_patho_proches_vide
    defaults: { _controller:UserBundle:User:liste_patho_proches_vide }

###
user_nous_contacter_1:
    path:     /nous_contacter
    defaults: { _controller:UserBundle:User:nous_contacter }

###
user_nous_contacter_2:
    path:     /nous_contacter_2
    defaults: { _controller:UserBundle:User:nous_contacter }

###
supprimer_compte_1:
    path:     /validation_supprimer
    defaults: {_controller:UserBundle:User:supprimer_compte_1 }

###
supprimer_compte_2:
    path:     /compte_supprime
    defaults: {_controller:UserBundle:User:supprimer_compte_2 }

# user_modifier_supprimer:
#     path:     /modifier_supprimer
#     defaults: { _controller:UserBundle:User:modifier_supprimer }

# user_modifier_infos_individu:
#     path:     /modifier_infos_individu
#     defaults: { _controller:UserBundle:User:modifier_infos_individu }

# user_supprimer_infos_individu:
#     path:     /supprimer_infos_individu
#     defaults: { _controller:UserBundle:User:supprimer_infos_individu }

# user_choix_patho_modifier:
#     path:     /choix_patho_modifier
#     defaults: { _controller:UserBundle:User:choix_patho_modifier }

# user_supprimer_patho_individu:
#     path:     /supprimer_patho_individu
#     defaults: { _controller:UserBundle:User:supprimer_patho_individu }

# user_ajouter_patho_individu:
#     path:     /ajouter_patho_individu
#     defaults: { _controller:UserBundle:User:ajouter_patho_individu }

# user_modifier_patho_individu:
#     path:     /modifier_patho_individu
#     defaults: { _controller:UserBundle:User:modifier_patho_individu }

# user_ajouter_proche:
#     path:     /ajouter_proche
#     defaults: { _controller:UserBundle:User:ajouter_proche }

# user_lister:
#     path:     /lister_membre
#     defaults: { _controller:UserBundle:User:lister_relation }

# user_liste_proches:
#     path:    /liste_proches
#     defaults: { _controller:UserBundle:User:liste_proches }

# user_liste_relations:
#     path:    /liste_relations
#     defaults: { _controller:UserBundle:User:liste_relations }