###
user_accueil:
    path:     /accueil
    defaults: { _controller:UserBundle:User:accueil }

###
user_connected_index:
    path:     /
    defaults: {_controller:UserBundle:User:index }

###
user_mon_compte:
    path:     /mon_compte
    defaults: { _controller:UserBundle:User:mon_compte }

user_mes_infos:
    path:     /mes_infos
    defaults: { _controller:UserBundle:User:mes_infos }

user_mes_infos_vide:
    path:     /mes_infos_vide
    defaults: { _controller:UserBundle:User:mes_infos_vide }

user_modifier_mes_infos:
    path:     /modifier_mes_infos
    defaults: { _controller:UserBundle:User:modifier_mes_infos }

user_mes_patho:
    path:     /mes_patho
    defaults: { _controller:UserBundle:User:mes_patho }

user_mes_patho_vide:
    path:     /mes_patho_vide
    defaults: { _controller:UserBundle:User:mes_patho_vide }

#
user_ajout_proche:
    path:     /ajout_proche
    defaults: { _controller:UserBundle:User:ajout_proche }

###
user_liste_proches:
    path:    /liste_proches
    defaults: { _controller:UserBundle:User:liste_proches }
###
user_liste_proches_vide:
    path:    /liste_proches_vide
    defaults: { _controller:UserBundle:User:liste_proches_vide }

###
user_infos_proche:
    path:     /infos_proche/{id_indiv}
    defaults: { _controller:UserBundle:User:infos_proche }

###
user_modif_proche:
    path:     /modif_proche/{id_indiv}
    defaults: { _controller:UserBundle:User:modif_proche }

user_liste_patho_proche:
    path:     /liste_patho_proche/{id_indiv}
    defaults: { _controller:UserBundle:User:liste_patho_proche }
user_liste_patho_proche_vide:
    path:     /liste_patho_proche_vide/{id_indiv}
    defaults: { _controller:UserBundle:User:liste_patho_proche_vide }

user_ajout_patho_proche:
    path:     /ajout_patho_proche/{id_indiv}
    defaults: { _controller:UserBundle:User:ajout_patho_proche }

user_modif_patho_proche:
    path:     /modif_patho_proche/{id_indiv}/{id_patho}
    defaults: { _controller:UserBundle:User:modif_patho_proche }

user_suppr_patho_proche:
    path:     /suppr_patho_proche/{id_indiv}/{id_patho}
    defaults: { _controller:UserBundle:User:suppr_patho_proche }

###
user_suppr_proche:
    path:     /suppr_proche/{id_indiv}
    defaults: { _controller:UserBundle:User:suppr_proche }

user_liste_patho_proches:
    path:    /liste_patho_proches
    defaults: { _controller:UserBundle:User:liste_patho_proches }
###
user_liste_patho_proches_vide:
    path:    /liste_patho_proches_vide
    defaults: { _controller:UserBundle:User:liste_patho_proches_vide }

###
user_nous_contacter_1:
    path:     /nous_contacter
    defaults: { _controller:UserBundle:User:nous_contacter }

###
user_nous_contacter_2:
    path:     /nous_contacter_2
    defaults: { _controller:UserBundle:User:nous_contacter }

###
supprimer_compte_1:
    path:     /validation_supprimer
    defaults: {_controller:UserBundle:User:supprimer_compte_1 }

###
supprimer_compte_2:
    path:     /compte_supprime
    defaults: {_controller:UserBundle:User:supprimer_compte_2 }


# user_modifier_supprimer:
#     path:     /modifier_supprimer
#     defaults: { _controller:UserBundle:User:modifier_supprimer }

# user_modifier_infos_individu:
#     path:     /modifier_infos_individu
#     defaults: { _controller:UserBundle:User:modifier_infos_individu }

# user_supprimer_infos_individu:
#     path:     /supprimer_infos_individu
#     defaults: { _controller:UserBundle:User:supprimer_infos_individu }

# user_choix_patho_modifier:
#     path:     /choix_patho_modifier
#     defaults: { _controller:UserBundle:User:choix_patho_modifier }

# user_supprimer_patho_individu:
#     path:     /supprimer_patho_individu
#     defaults: { _controller:UserBundle:User:supprimer_patho_individu }

# user_ajouter_patho_individu:
#     path:     /ajouter_patho_individu
#     defaults: { _controller:UserBundle:User:ajouter_patho_individu }

# user_modifier_patho_individu:
#     path:     /modifier_patho_individu
#     defaults: { _controller:UserBundle:User:modifier_patho_individu }

# user_ajouter_proche:
#     path:     /ajouter_proche
#     defaults: { _controller:UserBundle:User:ajouter_proche }

# user_lister:
#     path:     /lister_membre
#     defaults: { _controller:UserBundle:User:lister_relation }

# user_liste_proches:
#     path:    /liste_proches
#     defaults: { _controller:UserBundle:User:liste_proches }

# user_liste_relations:
#     path:    /liste_relations
#     defaults: { _controller:UserBundle:User:liste_relations }

# user_modif_proche:
#     path:     /modif_proche
#     defaults: { _controller:UserBundle:User:modif_proche }
