user_connected_index:
    path:     /
    defaults: {_controller:UserBundle:User:index }

user_accueil:
    path:     /accueil
    defaults: { _controller:UserBundle:User:accueil }

user_modifier:
    path:     /modifier
    defaults: { _controller:UserBundle:User:modifier }
 
user_ajouter:
    path:     /ajouter
    defaults: { _controller:UserBundle:User:ajouter }
    
user_supprimer:
    path:     /supprimer
    defaults: { _controller:UserBundle:User:supprimer }
